name: Autoreconf Dist

on:
  push:
    branches: [ dev ]

jobs:
  autoreconf:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Autotools
      run: sudo apt-get update && sudo apt-get install -y autoconf automake libtool sed 

    - name: Checkout Dev Branch
      uses: actions/checkout@v2
      with:
        ref: 'dev'

    - name: Run autoreconf
      run: |
        autoreconf -fiv
        ./configure

    - name: Push to Main Branch
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add -f config.guess config.sub configure 
        git commit -m "Auto-update Autotools files" || echo "No changes to commit"
        git push origin HEAD:main -f